- name: variables
  hosts: web
  vars:
    COURSE: "Devops with AWS"
    DURATION: "120HRS"
    TRAINER: "Siva"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, duration is: {{DURATION}}, Trainer: {{TRAINER}}"