- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false #not confidential
  - name: DURATION
    prompt: Please enter the course duration
    private: false #not confidential
  - name: TRAINER
    prompt: Please enter the trainer name
    private: false #not confidential
  tasks:
  - name: print variables from prompt
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, duration is: {{DURATION}}, trainer is: {{TRAINER}}"