- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hi I am l learning {{COURSE}}, duration is: {{DURATION}}, trainer is: {{TRAINER}}"