- name: variables from inventory
  hosts: web
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hi I am l learning {{COURSE}}, duration is: {{DURATION}}, trainer is: {{TRAINER}}"