- name: loop
  hosts: web
  become: yes
  tasks:
  - name: install packages with loop
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - postfix
    - httpd    