- name: filters demo
  hosts: local
  connection: local
  tasks:
  - name: variable-filters
    ansible.builtin.debug:
      msg: "Hi {{ course | default('Devops') }}"

  - name: convert to upper case
    vars:
      greetings: "Hello Hari"
    ansible.builtin.debug:
      msg: "{{ greetings | upper}}"

  - name: convert to lower case
    vars:
      greetings: "Hi Hari"
    ansible.builtin.debug:
      msg: "{{ greetings | lower}}"
    
  - name: print unique numbers
    vars:
      numbers: [1,2,3,66,77,3,2,1]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"
