- name: filters demo
  hosts: local
  connection: local
  tasks:
  - name: variable-filters
    ansible.builtin.debug:
      msg: "Hi {{ course | default('Devops') }}"

  - name: convert to upper case
    vars:
      greetings: "Hello Hari"
    ansible.builtin.debug:
      msg: "{{ greetings | upper}}"

  - name: convert to lower case
    vars:
      greetings: "Hi Hari"
    ansible.builtin.debug:
      msg: "{{ greetings | lower}}"
    
  - name: print unique numbers
    vars:
      numbers: [1,2,3,66,77,3,2,1]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: min and max numbers
    vars:
      numbers: [55,23,45,76,17,84]
    ansible.builtin.debug:
      msg: "Min: {{ numbers | min }} and Max: {{ numbers | max }}"

  - name: convert dictionary/map to list
    vars:
      course:
        name: "Devops with AWS"
        duration: 120
        trainer: "Siva"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert list to dictionary/map
    vars:
      course:
      - {"key": "name", "value": "Devops with AWS"}
      - {"key": "duration", "value": "120"}
      - {"key": "trainer", "value": "Siva"}
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"

  - name: check ip
    vars:
      myip: "52.201.249.235"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"
