- name: create ec2_instances and route53
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-078388c3d5e85af75"
    sg_id: "sg-00e1a95a1fec2404c"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: "nhari.online"
  tasks:
  - name: create ec2-instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
  
  - name: create route53 private IP
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.nhari.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}" #private IP address to create DNS
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create route53 public IP
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #nhari.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}" #public IP address to create DNS
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"